import React from 'react'

export default function Help() {
  return (
    <div className='text-center mt-28'>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta quo dolorem aliquid est necessitatibus. Maiores, vero eum dolorem provident cupiditate repudiandae sunt odit, expedita quaerat beatae non illum consequatur est. Repudiandae architecto ipsa laboriosam aliquam in! Eaque perferendis nisi amet repellat commodi nostrum, voluptatum molestiae fuga quisquam ratione maxime, architecto unde eveniet mollitia quod harum veritatis numquam ex ipsum! Odio, sit. Labore, odit accusantium porro tenetur enim numquam ullam aliquam dolor quasi earum aspernatur molestias iure inventore maxime vero reiciendis molestiae quod provident in id exercitationem! Excepturi, voluptatum. Omnis perferendis numquam dolores exercitationem. Accusantium amet laborum perferendis, possimus aut nulla obcaecati alias quo voluptatum corporis quam excepturi quod quos recusandae, eos consequatur doloribus harum earum voluptate maiores minus. Possimus odit blanditiis voluptates qui. Voluptatem, id expedita. Suscipit, non! Ipsa consequuntur perspiciatis nam inventore. Possimus officia voluptas aspernatur dolorem animi unde! Quae placeat aliquam aliquid ex veritatis, architecto neque distinctio a delectus fuga reiciendis nostrum alias est laborum deserunt debitis, perferendis illum, cum corrupti earum animi. Iusto suscipit ducimus magnam voluptate placeat a! Dolorem, accusamus maxime. Non repellendus commodi cum nihil et nulla hic quo debitis quisquam dicta? At adipisci minus repudiandae qui voluptatem. Tempore debitis atque, inventore amet id facere iste magni perspiciatis voluptatibus odit nemo, sit similique perferendis ad ut commodi, in cupiditate architecto aspernatur cumque vero? Dolorem incidunt obcaecati laborum. Ipsum minima rerum saepe eum aspernatur aut ex minus, dolorum, tempore omnis deserunt dignissimos tempora id similique ratione beatae praesentium temporibus facilis recusandae? Molestiae in laboriosam quidem omnis voluptate qui facilis nisi a voluptas suscipit natus earum iure tempora minima, enim iusto temporibus ipsum officiis culpa. Quod voluptate distinctio inventore reiciendis placeat. Est obcaecati neque eos fugiat a sit magni! Eos asperiores non necessitatibus hic. Blanditiis enim iure vitae pariatur assumenda. Distinctio quas cupiditate nobis qui quasi deserunt.
    </div>
  )
}
